import {Component} from 'react'
import {Cookies} from 'js-cookie'
import Loader from 'react-loader-spinner'
import NxtWatchContext from '../../context/NxtWatchContext'
import Header from '../Header'
import './index.css'
